modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/issues"
[[mods]]
modId= "${mod_id}"
version="${mod_version}"
displayName="Brass-Amber BattleTowers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/brassamberbattletowers"
logoFile="BrassAmberBattleTowers.png"
credits='''Inspired by BattleTowers from YogBox
           Translations by: SamleGamer, Kzeroko, RockYl, and BlackShadow77
           Music:
                Land Tower: Ancestry by Lena Raine
                Ocean Tower: Dragonfish by C418
                Core Tower: So Below by Lena Raine
                Nether Tower: Rubedo by Lena Raine
                End Tower:  Complex Radiation by LudoCrypt
                Sky Tower: Clouds by Emile van Kreiken
                
                Land Golem: Rage Of Bahryn'muul by Rotch Gwylt
                Ocean Golem: Void Of Moraizu'un by Rotch Gwylt
                Core Golem: Awakening Of Obthu'uryn by Rotch Gwylt
                Nether Golem: Throne Of Infuur'niir by Rotch Gwylte
                End Golem:  Mind Of Shul'losniir by Rotch Gwylt
                Sky Golem: Descent Of Veyhz'kriin by Rotch Gwylt
           '''

authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
# [[dependencies.ba_bt]]
  #  modId="lootr"
  #  mandatory=false
  #  versionRange="[0.2.20.57,)"
  #  ordering="NONE"
  #  side="BOTH"


